/* OCR H573 — A-Level Religious Studies revision content */
const CONTENT = { "01":{title:"",code:"",intro:"",topics:[]}, "02":{title:"",code:"",intro:"",topics:[]}, "03":{title:"",code:"",intro:"",topics:[]} };

CONTENT["01"] = {
  title: "Philosophy of Religion",
  code: "H573/01",
  intro: "This paper runs from the Greek metaphysics that gave Christianity its conceptual vocabulary through to the twentieth-century attempts to declare religious language meaningless. Nine topics, each probing whether belief in God can be rationally defended, experientially grounded, or coherently spoken about.",
  topics: [
    {id:"plato-aristotle",title:"Ancient Philosophical <em>Influences</em>",
      spec:["Plato: Forms, Cave, reason","Aristotle: Four Causes, Prime Mover","Rationalism vs empiricism"],
      orientation:"Two foundational answers to a single question: what is ultimately real, and how do we access it? Plato says reality is immaterial and accessed by reason; Aristotle says it is the world in front of us and accessed by the senses.",
      ao1:"<h3>Plato: the Theory of Forms</h3><p>The sensible world is unstable. Reality consists of <strong>Forms</strong>: perfect, immaterial, eternal archetypes. Crowned by the <strong>Form of the Good</strong>. Plato is a <strong>rationalist</strong>: the senses deceive, reason reveals.</p><h4>The Analogy of the Cave</h4><p>Prisoners mistake shadows for reality. One escapes, sees sunlight, returns to free the others. The Cave dramatises the philosopher's ascent to knowledge of the Good.</p><h3>Aristotle: the Four Causes and Prime Mover</h3><p>Forms are <em>in</em> things. The <strong>Four Causes</strong>:</p><ol><li><strong>Material</strong></li><li><strong>Formal</strong></li><li><strong>Efficient</strong></li><li><strong>Final</strong> (<em>telos</em>)</li></ol><p>An infinite regress of movers is impossible, so there must be a <strong>Prime Mover</strong>: pure actuality, immaterial, unchanging. Aristotle is an <strong>empiricist</strong>.</p>",
      ao2:"<h3>Plato's Forms: do they do any work?</h3><p>Aristotle's Third Man objection: the theory multiplies entities. Plato never specifies 'participation'.</p><h3>Aristotle's Prime Mover</h3><p>Impersonal, indifferent. Not worship-worthy in any biblical sense. Aquinas later Christianises it.</p><h3>Rationalism vs empiricism</h3><p>A serious philosopher of religion needs both: Plato for transcendence, Aristotle for immanence.</p>",
      thesis:{line:"Aristotle wins the <em>methodological</em> battle, but Plato wins the <em>metaphysical</em> one.",unpacking:"Aristotle's empirical method is more disciplined but his Prime Mover is too thin. Plato's Form of the Good retains normative weight. The synthesis arrived with Aquinas."},
      quote:{text:"The Good is not essence, but far exceeds essence in dignity and power.",cite:"Plato, Republic 509b"},
      scholars:[{name:"Heraclitus",pos:"Reality is flux; the background Plato rejects."},{name:"Russell",pos:"Modified Platonism about universals."},{name:"Nussbaum",pos:"Reads Aristotle as more humane than Plato."},{name:"Popper",pos:"Republic as totalitarian."}],
      exam:"Critically assess the view that Plato's understanding of reality is more convincing than Aristotle's. [40]"
    },
    {id:"soul-mind-body",title:"Soul, Mind <em>&amp;</em> Body",
      spec:["Plato on the soul","Aristotle on the soul","Descartes' substance dualism","Materialism"],
      orientation:"What is a person? A Greek philosopher, a Frenchman, and a behaviourist give incompatible answers. The stakes are theological: if the soul is fiction, so is eternal life.",
      ao1:"<h3>Plato</h3><p>The soul is immaterial, pre-exists the body, survives its death. Learning is recollection (<em>anamnesis</em>).</p><h3>Aristotle</h3><p>The soul is the <strong>form</strong> of the living body. Not separable.</p><h3>Descartes</h3><p>Two substances: <strong>res extensa</strong> and <strong>res cogitans</strong>. I can doubt the body but not the doubting mind.</p><h3>Materialism</h3><p><strong>Ryle</strong>: substance dualism is the 'ghost in the machine', a category error. <strong>Dawkins</strong>: soul is metaphor.</p>",
      ao2:"<h3>The interaction problem</h3><p>If soul is immaterial, how does it move the body? Elisabeth of Bohemia pressed this on Descartes; he had no answer.</p><h3>Materialism on trial</h3><p>Jackson's Mary; Nagel's bat. <strong>Qualia</strong> resist reduction.</p><h3>Aristotle's middle way</h3><p>Hylomorphism avoids both problems. Close to non-reductive physicalism.</p>",
      thesis:{line:"Descartes' dualism is indefensible and crude materialism cannot explain consciousness; <em>Aristotle's hylomorphism</em> is the only view standing.",unpacking:"The interaction problem kills substance dualism, qualia kill eliminative materialism. Aristotle preserves what is true in each."},
      quote:{text:"If the eye were a living creature, its soul would be its sight.",cite:"Aristotle, De Anima II.1"},
      scholars:[{name:"Ryle",pos:"'Ghost in the machine'; category error."},{name:"Jackson",pos:"Mary's room — qualia are real."},{name:"Nagel",pos:"What is it like to be a bat?"},{name:"Chalmers",pos:"The 'hard problem' of consciousness."},{name:"Elisabeth of Bohemia",pos:"Pressed Descartes on interaction (1643)."}],
      exam:"\"The concept of the soul is best understood metaphorically.\" Discuss. [40]"
    },
    {id:"observation",title:"Arguments from <em>Observation</em>",
      spec:["Teleological argument","Cosmological argument","Hume's critique","Evolution"],
      orientation:"If God exists, the world should show it. The teleological argument reads the universe for signs of design; the cosmological asks why anything exists at all.",
      ao1:"<h3>Teleological argument</h3><p><strong>Aquinas' Fifth Way</strong>: unintelligent things act towards ends. <strong>Paley's watch</strong>: arrangement of parts for a purpose implies a watchmaker.</p><h3>Cosmological argument</h3><p>Aquinas' first three Ways: <strong>motion, causation, contingency</strong>. Infinite regress impossible; therefore First Mover / Cause / Necessary Being.</p><h3>Hume's critique</h3><ul><li>Analogy of universe and machine is weak</li><li>Proves only a designer, not the omni-God</li><li>Order may arise from chance</li></ul><h3>Evolution</h3><p>Darwin provides a naturalistic mechanism. Dawkins' 'blind watchmaker'.</p>",
      ao2:"<h3>Does teleology survive evolution?</h3><p>Paley's biological argument is dead. But <strong>fine-tuning</strong> (physical constants) survives.</p><h3>Does cosmological argument jump too fast?</h3><p>Russell to Copleston: 'The universe is just there, and that's all.'</p><h3>A posteriori arguments</h3><p>Make God more probable, not necessary; but more honest than a priori.</p>",
      thesis:{line:"Paley was routed by Darwin and Aquinas was softened by Hume, but <em>fine-tuning and contingency refuse to stay dead</em>.",unpacking:"The eighteenth-century arguments fail in their original forms, but modern physics hands teleology a second life through fine-tuning."},
      quote:{text:"The machine of the universe is by no means so striking an analogy as the world of vegetation.",cite:"Hume, Dialogues VII"},
      scholars:[{name:"Copleston",pos:"Pressed PSR in his 1948 debate with Russell."},{name:"Russell",pos:"'The universe is just there.'"},{name:"Swinburne",pos:"Fine-tuning revives teleology."},{name:"Collins",pos:"Bayesian fine-tuning."}],
      exam:"\"The cosmological argument simply jumps to the conclusion of a transcendent creator.\" Discuss. [40]"
    },
    {id:"reason",title:"Arguments from <em>Reason</em>",
      spec:["Anselm's ontological argument","Gaunilo's critique","Kant on existence as predicate"],
      orientation:"The one argument that claims to prove God from the concept of God alone.",
      ao1:"<h3>Anselm</h3><p><strong>Proslogion 2</strong>: God is 'that than which nothing greater can be conceived'. To exist in reality is greater than to exist only in understanding. So God exists.</p><p><strong>Proslogion 3</strong>: God exists <strong>necessarily</strong>.</p><h3>Gaunilo</h3><p>The same logic proves a perfect island. Reductio.</p><h3>Kant</h3><p>Existence is not a predicate. 100 real thalers are no richer in concept than 100 imagined ones.</p>",
      ao2:"<h3>Does Gaunilo land?</h3><p>An island is contingent; the parody misses Proslogion 3.</p><h3>Kant</h3><p>Existence is a second-order property (Frege, Russell).</p><h3>Modal rescue</h3><p>Malcolm, Plantinga: necessary existence <em>is</em> a predicate. But the premise 'a necessary being is possible' is what the atheist denies.</p>",
      thesis:{line:"The ontological argument is <em>formally ingenious and practically worthless</em>; it convinces only those who already believe.",unpacking:"Kant is essentially right, and Plantinga's modal rescue buys validity at the price of a premise no atheist will grant."},
      quote:{text:"Something than which nothing greater can be conceived cannot exist in the understanding alone.",cite:"Anselm, Proslogion 2"},
      scholars:[{name:"Malcolm",pos:"Revived Proslogion 3."},{name:"Plantinga",pos:"Modal ontological argument."},{name:"Frege",pos:"Existence is a second-order predicate."},{name:"Hartshorne",pos:"Process-theological modal argument."}],
      exam:"\"The ontological argument shows that God must exist.\" Discuss. [40]"
    },
    {id:"religious-experience",title:"Religious <em>Experience</em>",
      spec:["Mystical experience","Conversion","William James","Critiques"],
      orientation:"Millions claim to have encountered God directly. Are they right, deceived, or ill?",
      ao1:"<h3>William James</h3><p>Four marks of <strong>mystical experience</strong>:</p><ol><li><strong>Ineffable</strong></li><li><strong>Noetic</strong></li><li><strong>Transient</strong></li><li><strong>Passive</strong></li></ol><p>Judge experience by its fruits.</p><h3>Types</h3><p><strong>Mystical</strong>: Teresa of Avila; Otto's <em>mysterium tremendum et fascinans</em>. <strong>Conversion</strong>: Saul on the Damascus road.</p><h3>Naturalistic explanations</h3><ul><li><strong>Psychological</strong>: Freud — wish-fulfilment</li><li><strong>Physiological</strong>: temporal lobe epilepsy</li><li><strong>Sociological</strong>: cultural patterning</li></ul>",
      ao2:"<h3>Swinburne's principles</h3><p><strong>Credulity</strong> and <strong>Testimony</strong>: experience has <em>prima facie</em> evidential weight.</p><h3>Cross-cultural problem</h3><p>If content tracks culture, evidence is compromised. Hick's pluralism saves it at a cost.</p><h3>Naturalistic explanations overreach</h3><p>Wish-fulfilment explains everything; therefore nothing specific.</p>",
      thesis:{line:"Religious experience is <em>rationally respectable but evidentially modest</em>: it can ground the believer but cannot convert the sceptic.",unpacking:"Swinburne's principles rightly treat experience as defeasible evidence, but cross-cultural variation means experience cannot establish the specific content of any religion."},
      quote:{text:"The further limits of our being plunge into an altogether other dimension of existence.",cite:"William James, Varieties"},
      scholars:[{name:"Otto",pos:"The numinous; mysterium tremendum."},{name:"Swinburne",pos:"Credulity and testimony principles."},{name:"Persinger",pos:"Temporal-lobe stimulation."},{name:"Stace",pos:"Cross-cultural unity beneath variation."},{name:"Katz",pos:"All experience is conceptually mediated."}],
      exam:"Critically assess the view that religious experience provides a basis for belief in God. [40]"
    },
    {id:"problem-of-evil",title:"The Problem of <em>Evil</em>",
      spec:["Logical and evidential problems","Augustine's theodicy","Hick's Irenaean theodicy"],
      orientation:"Epicurus: is God willing to prevent evil but not able? Then he is not omnipotent. Able but not willing? Then he is malevolent.",
      ao1:"<h3>The two problems</h3><p><strong>Logical (Mackie)</strong>: omnipotence + omnibenevolence + evil = inconsistent triad.</p><p><strong>Evidential (Rowe)</strong>: the fawn in the forest fire.</p><h3>Augustine</h3><p>Evil is <strong>privatio boni</strong>. The Fall corrupts human nature. <strong>Original Sin</strong>. Natural evil is punishment.</p><h3>Hick (Irenaean)</h3><p>The world is a <strong>vale of soul-making</strong>. Suffering builds character. Universalist.</p>",
      ao2:"<h3>Augustine</h3><p>Literal Fall is scientifically untenable. Biological transmission of sin is obscene. Schleiermacher: a perfect creation cannot produce corruption without already containing it.</p><h3>Hick</h3><p>Quantity and distribution problems. Children with cancer do not develop character. D.Z. Phillips: monstrous.</p><h3>Plantinga</h3><p>Free-will defence answers logical problem; evidential problem stands.</p>",
      thesis:{line:"Both classical theodicies fail: <em>Augustine's is incoherent, Hick's is inhumane</em>; the honest theist must concede evil as mystery, not solve it as puzzle.",unpacking:"Augustine collapses because a perfect creation cannot produce corruption without containing it. Hick's soul-making fails on children and animals."},
      quote:{text:"It is precisely the sense of its meaninglessness that is unbearable.",cite:"D.Z. Phillips"},
      scholars:[{name:"Mackie",pos:"Inconsistent triad."},{name:"Rowe",pos:"Fawn in the forest fire."},{name:"Plantinga",pos:"Free-will defence."},{name:"Adams (Marilyn McCord)",pos:"Horrendous evils; eschatological defeat."},{name:"Wykstra",pos:"Sceptical theism (CORNEA)."}],
      exam:"\"The existence of evil proves that there is no God.\" Discuss. [40]"
    },
    {id:"attributes-god",title:"The Nature <em>of</em> God",
      spec:["Omnipotence","Omniscience","Omnibenevolence","Eternity (Boethius, Anselm, Swinburne)"],
      orientation:"Traditional theism ascribes omniscience, omnipotence, omnibenevolence, and eternity to God. These attributes appear to conflict.",
      ao1:"<h3>Boethius</h3><p>God exists <strong>eternally</strong>, outside time: 'the complete possession all at once of illimitable life'. He sees, not foresees.</p><h3>Anselm</h3><p>Four-dimensionalist: God experiences all times as present.</p><h3>Swinburne</h3><p>God is <strong>everlasting</strong>: in time without beginning or end. Self-limited omnipotence and omniscience.</p><h3>The stone paradox</h3><p>Standard solution: incoherent task.</p>",
      ao2:"<h3>Boethius</h3><p>Solves freedom only if a being can coherently exist outside time.</p><h3>Swinburne</h3><p>Coherent but revisionary. Preserves a loving, responsive God at the cost of classical omniscience. Kenosis has biblical support.</p><h3>Which attribute gives?</h3><p>Deny libertarian freedom; deny comprehensive foreknowledge; or deny temporal divine action.</p>",
      thesis:{line:"<em>Swinburne's everlasting, self-limiting God</em> is philosophically coherent; Boethius' eternal God is devotionally compelling but metaphysically brittle.",unpacking:"A God who cannot respond is not the God of Abraham."},
      quote:{text:"Eternity is the complete possession all at once of illimitable life.",cite:"Boethius, Consolation V.6"},
      scholars:[{name:"Kenny",pos:"Classical attributes inconsistent."},{name:"Stump",pos:"ET-simultaneity defence of eternity."},{name:"Wolterstorff",pos:"God Everlasting."},{name:"Craig (William Lane)",pos:"Timeless without creation, temporal since."}],
      exam:"\"God's omniscience is incompatible with human free will.\" Discuss. [40]"
    },
    {id:"religious-language-1",title:"Religious Language: <em>Negative, Analogical, Symbolic</em>",
      spec:["Via negativa","Via positiva","Aquinas: analogy","Tillich: symbol"],
      orientation:"If God is infinite, can finite human words describe him?",
      ao1:"<h3>Via negativa</h3><p>Pseudo-Dionysius, Maimonides: only negations preserve transcendence.</p><h3>Aquinas: analogy</h3><p>Neither univocal nor equivocal but <strong>analogical</strong>. <strong>Attribution</strong> ('healthy') and <strong>proper proportion</strong>.</p><h3>Tillich: symbol</h3><p>Symbols participate in what they signify. 'God' is the supreme symbol pointing to <strong>ultimate concern</strong>.</p>",
      ao2:"<h3>Via negativa</h3><p>Davies: leaves nothing to worship.</p><h3>Analogy</h3><p>Threads the needle. Scotus: analogy collapses into univocity or equivocation.</p><h3>Tillich</h3><p>Cannot discriminate between rival theologies.</p>",
      thesis:{line:"<em>Aquinas is right</em>: negative theology is too thin, symbolism too slippery, analogy alone says something while preserving transcendence.",unpacking:"The via negativa is a discipline within analogy."},
      quote:{text:"In this life we do not see the essence of God. We know Him from creatures.",cite:"Aquinas, ST I.13.1"},
      scholars:[{name:"Davies",pos:"Decisive critique of negative theology."},{name:"Scotus",pos:"Against analogy."},{name:"Maimonides",pos:"Negative theology."},{name:"Tillich",pos:"Religious symbols."}],
      exam:"\"The via negativa is the only honest approach to religious language.\" Discuss. [40]"
    },
    {id:"religious-language-2",title:"Religious Language: <em>20th Century</em>",
      spec:["Logical positivism","Verification","Wittgenstein","Falsification"],
      orientation:"The twentieth-century claim that religious language is not false but meaningless.",
      ao1:"<h3>Ayer</h3><p>Verification principle: meaningful only if analytic or empirically verifiable.</p><h3>Falsification (Flew)</h3><p>The gardener parable: 'death by a thousand qualifications'.</p><h3>Hare: bliks</h3><p>Unfalsifiable but meaningful frameworks.</p><h3>Mitchell: partisan</h3><p>Faith is qualified but not surrendered.</p><h3>Wittgenstein</h3><p>Religious language is a <strong>language game</strong>.</p>",
      ao2:"<h3>Verificationism self-destructs</h3><p>The principle itself is neither analytic nor empirically verifiable.</p><h3>Mitchell beats Flew</h3><p>Responsible theism does treat evidence seriously.</p><h3>Wittgenstein</h3><p>Makes religious language non-cognitive. Satisfies the philosopher, dissatisfies the believer.</p>",
      thesis:{line:"Logical positivism is dead and Wittgensteinian non-cognitivism is a retreat; <em>Aquinas' analogical realism</em> remains the strongest account.",unpacking:"The verification principle is self-refuting. Wittgenstein makes religious language safe by emptying its content."},
      quote:{text:"A fine brash hypothesis may thus be killed by inches, the death by a thousand qualifications.",cite:"Antony Flew"},
      scholars:[{name:"Ayer",pos:"Verification principle."},{name:"Flew",pos:"Falsification."},{name:"Hare",pos:"Bliks."},{name:"Mitchell",pos:"The partisan parable."},{name:"Wittgenstein",pos:"Language games."},{name:"Phillips",pos:"Non-cognitive religion."}],
      exam:"\"Religious language is only meaningful if it is cognitive.\" Discuss. [40]"
    }
  ]
};

CONTENT["02"] = {
  title: "Religion and Ethics",
  code: "H573/02",
  intro: "Four normative theories (two religious, two secular), two applied topics, plus meta-ethics, conscience, and sexual ethics. The paper rewards students who apply theories sharply and evaluate decisively.",
  topics: [
    {id:"natural-law",title:"Natural <em>Law</em>",
      spec:["Telos","Four tiers of law","Primary and secondary precepts","Doctrine of double effect"],
      orientation:"Aquinas' theory: reason discerns the moral law because it is built into human nature.",
      ao1:"<h3>Telos and the four tiers</h3><p>Eternal Law → Divine Law → Natural Law → Human Law. The summum bonum is union with God.</p><h3>The precepts</h3><p><strong>Primary</strong>: preservation of life, ordered society, worship, education, reproduction.</p><p><strong>Secondary</strong>: derived by reason.</p><h3>Double effect</h3><p>Act with good and evil effects permissible if act not intrinsically evil, only good intended, good not by means of evil, proportionate.</p>",
      ao2:"<h3>Does human nature have a telos?</h3><p>Modern biology finds no teleology. Nietzsche: theological residue. <strong>Finnis</strong>: basic goods grasped by practical reason.</p><h3>Too rigid or too flexible?</h3><p>Double effect opens the door to consequentialist reasoning.</p><h3>Naturalistic fallacy</h3><p>Hume's is/ought; Moore's open question.</p>",
      thesis:{line:"Natural law <em>succeeds as an internal Catholic ethic but fails as the universal rational theory it claims to be</em>.",unpacking:"Aquinas' method depends on a teleological view of nature modern science cannot supply."},
      quote:{text:"Law is an ordinance of reason for the common good, promulgated by him who has care of the community.",cite:"Aquinas, ST I-II.90.4"},
      scholars:[{name:"Finnis",pos:"New natural law: seven basic goods."},{name:"MacIntyre",pos:"Recovery of Aristotelian-Thomist tradition."},{name:"Hume",pos:"Is/ought gap."},{name:"Hoose",pos:"Proportionalism."}],
      exam:"\"Natural law provides a reliable method of moral decision-making.\" Discuss. [40]"
    },
    {id:"situation-ethics",title:"Situation <em>Ethics</em>",
      spec:["Agape","Six propositions","Four working principles","Conscience as a verb"],
      orientation:"Fletcher's reply to legalism. Christian ethics has one rule: love.",
      ao1:"<h3>Agape</h3><p>Self-giving, unconditional love. Sole moral absolute.</p><h3>Six propositions</h3><ol><li>Only love is intrinsically good</li><li>Love replaces law</li><li>Love and justice are the same</li><li>Love wills the neighbour's good</li><li>End justifies means</li><li>Love decides situationally</li></ol><h3>Four working principles</h3><p>Pragmatism, relativism, positivism, personalism.</p>",
      ao2:"<h3>Strengths</h3><p>Captures something Christian (Mark 2:27).</p><h3>Weaknesses</h3><p><strong>Subjectivism</strong>; <strong>epistemic problem</strong>; <strong>Barclay</strong>: fine for saints, dangerous for sinners.</p><h3>Agape alone?</h3><p>Without specific precepts, the theory has no bite.</p>",
      thesis:{line:"Situation ethics rightly centres love but wrongly discards the rules that love requires; it is a <em>corrective to legalism, not a replacement for it</em>.",unpacking:"Without rules, selfishness rationalises as love."},
      quote:{text:"Love is the boss principle. It is not simply one principle among many.",cite:"Joseph Fletcher"},
      scholars:[{name:"Barclay",pos:"Fine for saints, dangerous for sinners."},{name:"Niebuhr",pos:"Love is impossible ideal."},{name:"Hauerwas",pos:"Virtue over situation."},{name:"Ramsey",pos:"Christian critique of Fletcher."}],
      exam:"\"Situation ethics is too subjective to be a reliable ethical theory.\" Discuss. [40]"
    },
    {id:"kant",title:"Kantian <em>Ethics</em>",
      spec:["Duty","Categorical imperative","Three formulations","Postulates"],
      orientation:"The most influential deontology. Morality is pure reason, indifferent to consequences.",
      ao1:"<h3>Duty</h3><p>'Nothing in the world can be called good without qualification, except a good will.'</p><h3>Categorical imperative</h3><ol><li><strong>Universal Law</strong></li><li><strong>Humanity</strong>: end, never means only</li><li><strong>Kingdom of Ends</strong></li></ol><h3>Three postulates</h3><p>Freedom, immortality, God.</p>",
      ao2:"<h3>Strengths</h3><p>Grounds human dignity.</p><h3>Lying problem</h3><p>The murderer at the door.</p><h3>Conflicting duties</h3><p>Ross' prima facie duties.</p><h3>Too rationalist</h3><p>Williams: 'moral saint' alien. Schiller: makes us despise inclination.</p>",
      thesis:{line:"Kantian ethics is the <em>best available foundation for human rights but too austere to be a complete moral theory</em>; it needs Aristotelian virtue to be livable.",unpacking:"Morality is also about character and relationship, which Kant undervalues."},
      quote:{text:"Act so that you treat humanity always as an end and never as a means only.",cite:"Kant, Groundwork II"},
      scholars:[{name:"O'Neill",pos:"Kantian global justice."},{name:"Korsgaard",pos:"Sources of normativity."},{name:"Ross",pos:"Prima facie duties."},{name:"Williams",pos:"Moral saint critique."}],
      exam:"\"Kantian ethics is too abstract to be useful.\" Discuss. [40]"
    },
    {id:"utilitarianism",title:"<em>Utilitarianism</em>",
      spec:["Bentham","Mill","Singer","Act vs rule"],
      orientation:"The greatest happiness of the greatest number.",
      ao1:"<h3>Bentham</h3><p>Act utilitarianism. Hedonic calculus.</p><h3>Mill</h3><p>Higher and lower pleasures. 'Better to be Socrates dissatisfied than a pig satisfied.'</p><h3>Singer</h3><p>Preference utilitarianism. Extends to animals.</p>",
      ao2:"<h3>Strengths</h3><p>Impartial, scientific, democratic.</p><h3>Justice problem</h3><p>Williams' sheriff. McCloskey's organ harvest.</p><h3>Calculation</h3><p>Pleasures incommensurable.</p><h3>Demandingness</h3><p>Singer's conclusions are monstrous if true.</p>",
      thesis:{line:"Utilitarianism is <em>indispensable for public policy and indefensible as a complete moral theory</em>; it tracks aggregate good brilliantly and individual rights disastrously.",unpacking:"No serious theorist can do without utility. But framing the innocent is not policy."},
      quote:{text:"The greatest happiness of the greatest number is the foundation of morals and legislation.",cite:"Bentham"},
      scholars:[{name:"Williams",pos:"Sheriff case; integrity objection."},{name:"Nozick",pos:"Utility monster; experience machine."},{name:"Rawls",pos:"Does not take distinction between persons seriously."},{name:"Singer",pos:"Preference utilitarianism."}],
      exam:"\"Utilitarianism is the best approach to moral decision-making.\" Discuss. [40]"
    },
    {id:"euthanasia",title:"<em>Euthanasia</em>",
      spec:["Sanctity of life","Quality of life","Voluntary","Non-voluntary"],
      orientation:"The applied topic that forces abstract theory to confront real suffering.",
      ao1:"<h3>Key concepts</h3><ul><li>Sanctity of life (imago Dei)</li><li>Quality of life</li><li>Voluntary / non-voluntary / involuntary</li><li>Active / passive</li></ul><h3>Theory applications</h3><p>Natural Law: absolute opposition. Situation Ethics: context. Kant: traditionally opposed. Utilitarianism: permissive.</p>",
      ao2:"<h3>Sanctity or quality?</h3><p>Brain-death legislation already treats life as conditional. <strong>Singer</strong>: sanctity incoherent.</p><h3>Autonomy</h3><p>Mill: over one's own body, the individual is sovereign.</p><h3>Slippery slope</h3><p>Mixed evidence.</p><h3>Killing vs letting die</h3><p>Rachels: no moral difference.</p>",
      thesis:{line:"Voluntary euthanasia is <em>morally permissible</em> for competent, terminally ill patients.",unpacking:"Sanctity of life cannot sustain the weight imposed once quality-of-life judgements enter medicine elsewhere."},
      quote:{text:"To extend a life when death is imminent and inevitable is not to preserve it but merely to prolong dying.",cite:"Jonathan Glover"},
      scholars:[{name:"Rachels",pos:"No moral difference: killing/letting die."},{name:"Singer",pos:"Sanctity incoherent."},{name:"Glover",pos:"Utilitarian defence of voluntary euthanasia."},{name:"John Paul II",pos:"Evangelium Vitae."}],
      exam:"\"Euthanasia can never be justified.\" Discuss. [40]"
    },
    {id:"business-ethics",title:"Business <em>Ethics</em>",
      spec:["Corporate social responsibility","Whistle-blowing","Globalisation"],
      orientation:"Does business have moral obligations beyond profit?",
      ao1:"<h3>Friedman</h3><p>The social responsibility of business is to increase its profits.</p><h3>Stakeholder theory</h3><p>Freeman: corporations affect many stakeholders.</p><h3>Whistle-blowing</h3><p>Kant: duty to truth. Utilitarian: disclose if benefits exceed costs.</p><h3>Globalisation</h3><p>Reduces global poverty; widens inequality. Rana Plaza (2013).</p>",
      ao2:"<h3>Is Friedman right?</h3><p>Force against naive CSR. But corporations affect non-shareholders massively.</p><h3>Is CSR sincere?</h3><p>'Hypocritical window-dressing.' But imperfect CSR is better than none.</p><h3>Whistle-blowers</h3><p>Strong defence; weak institutional support.</p>",
      thesis:{line:"Friedman's shareholder doctrine is the ideology of the last generation; <em>coherent business ethics treats corporations as powerful agents with duties proportionate to their power</em>.",unpacking:"A corporation that can move economies is not merely a profit-making instrument."},
      quote:{text:"The social responsibility of business is to increase its profits.",cite:"Milton Friedman, NYT 1970"},
      scholars:[{name:"Friedman",pos:"Shareholder primacy."},{name:"Freeman",pos:"Stakeholder theory."},{name:"Carroll",pos:"Pyramid of CSR."},{name:"Klein",pos:"Systemic critique."}],
      exam:"\"Good ethics is good business.\" Discuss. [40]"
    },
    {id:"meta-ethics",title:"<em>Meta-Ethics</em>",
      spec:["Naturalism","Intuitionism","Emotivism"],
      orientation:"Not how to live but what we are saying when we say someone should.",
      ao1:"<h3>Naturalism</h3><p>Moral properties are natural properties. Moore's <strong>naturalistic fallacy</strong>.</p><h3>Intuitionism</h3><p>Moore: 'good' is simple, non-natural, grasped by intuition. Ross: prima facie duties.</p><h3>Emotivism</h3><p>Ayer, Stevenson: 'boo/hurrah' theory.</p>",
      ao2:"<h3>Naturalism's fate</h3><p>Cornell realists: non-reductive naturalism survives.</p><h3>Intuitionism's problem</h3><p>Intuitions vary; cannot explain moral progress.</p><h3>Emotivism's collapse</h3><p>Cannot explain moral disagreement or reasoning.</p>",
      thesis:{line:"Emotivism is false, intuitionism is incomplete, and <em>a cautious naturalism-plus-intuition</em> is the best available account.",unpacking:"Tied to human flourishing, corrected by reflective intuition."},
      quote:{text:"If a man confesses that he has no moral feelings about a thing, we mean that he has no reasons of a certain kind to act.",cite:"Ayer"},
      scholars:[{name:"Moore",pos:"Naturalistic fallacy; intuitionism."},{name:"Ross",pos:"Prima facie duties."},{name:"Hare",pos:"Prescriptivism."},{name:"Mackie",pos:"Error theory."}],
      exam:"\"Ethical statements are no more than expressions of feeling.\" Discuss. [40]"
    },
    {id:"conscience",title:"<em>Conscience</em>",
      spec:["Aquinas: ratio, synderesis, conscientia","Freud: id, ego, super-ego"],
      orientation:"Aquinas: conscience is reason discerning God's law. Freud: it is the internalised parent.",
      ao1:"<h3>Aquinas</h3><ul><li><strong>Ratio</strong>: reason</li><li><strong>Synderesis</strong>: innate disposition; infallible</li><li><strong>Conscientia</strong>: application; fallible</li><li><strong>Vincible / invincible ignorance</strong></li></ul><h3>Freud</h3><p><strong>Id</strong> / <strong>Ego</strong> / <strong>Super-ego</strong>.</p><h3>Fromm</h3><p>Authoritarian vs humanistic conscience.</p>",
      ao2:"<h3>On guilt</h3><p>Aquinas: real failure. Freud: often neurotic.</p><h3>On God</h3><p>Aquinas: divine source. Freud: projection.</p><h3>Modern psychology</h3><p>Conscience is plural: emotion, social learning, reasoning, identity (Haidt).</p>",
      thesis:{line:"Aquinas is right that moral reasoning is real but wrong to locate it in a single divine faculty; Freud is right that upbringing shapes moral emotion but wrong to reduce conscience to it; <em>neither alone is adequate</em>.",unpacking:"Conscience is reason, emotion, identity, and social learning together."},
      quote:{text:"The voice of conscience is so delicate that it is easy to stifle it; but also so clear it is impossible to mistake.",cite:"Madame de Staël"},
      scholars:[{name:"Fromm",pos:"Authoritarian vs humanistic."},{name:"Newman",pos:"Conscience as voice of God."},{name:"Butler",pos:"Conscience as superintendent faculty."},{name:"Haidt",pos:"Intuition precedes reasoning."}],
      exam:"\"Freud's account of conscience is more convincing than Aquinas'.\" Discuss. [40]"
    },
    {id:"sexual-ethics",title:"Sexual <em>Ethics</em>",
      spec:["Premarital","Extramarital","Homosexuality"],
      orientation:"Where traditional moral theology most visibly diverges from modern secular opinion.",
      ao1:"<h3>Traditional teaching</h3><p>Sex for marriage. Adultery condemned. Homosexual acts condemned (Leviticus, Romans 1).</p><h3>Modern reappraisals</h3><p>Catholic: orientation not sinful, acts are. Mainline Protestant communions split.</p><h3>Theory applications</h3><ul><li>Natural Law: telos = procreation in marriage</li><li>Situation: loving option</li><li>Kant: consent</li><li>Utilitarian: maximise welfare</li></ul>",
      ao2:"<h3>Religion's contribution</h3><p>Selective scriptural application looks motivated.</p><h3>Autonomy</h3><p>Mill's harm principle settles legal, not moral, question.</p><h3>Homosexuality</h3><p>Natural law cannot consistently exclude same-sex relationships while permitting infertile heterosexual sex.</p>",
      thesis:{line:"Traditional sexual ethics <em>retains moral insight into commitment and family but loses the argument on homosexuality by its own principles</em>.",unpacking:"Consent is the ceiling of law; not the whole of moral thought."},
      quote:{text:"The only purpose for which power can be rightfully exercised over any member of a civilised community is to prevent harm to others.",cite:"Mill, On Liberty"},
      scholars:[{name:"Finnis",pos:"Traditional natural law on sexuality."},{name:"Farley",pos:"Just Love; Catholic feminist framework."},{name:"Rogers",pos:"Theological argument for same-sex marriage."},{name:"Foucault",pos:"Sexual ethics historically constructed."}],
      exam:"\"Religious ethical approaches still have relevance to modern sexual ethics.\" Discuss. [40]"
    }
  ]
};

CONTENT["03"] = {
  title: "Developments in Christian Thought",
  code: "H573/03",
  intro: "Christian thought from Augustine to liberation theology. Twelve topics organised into insight, foundations, living, development, society, and challenges.",
  topics: [
    {id:"augustine",title:"Augustine on <em>Human Nature</em>",
      spec:["Pre- and post-Fall","Original Sin","Grace and summum bonum"],
      orientation:"The theologian who fixed Christian pessimism about human nature for a thousand years.",
      ao1:"<h3>Pre-Fall</h3><p>Perfect friendship with God; reason ordered.</p><h3>The Fall</h3><p>Will turns inward (<em>incurvatus in se</em>).</p><h3>Original Sin</h3><p>Transmitted biologically. Every human born fallen.</p><h3>Grace</h3><p>'Our heart is restless until it rests in thee.'</p>",
      ao2:"<h3>Historical Fall untenable</h3><p>Evolutionary biology denies a single human pair.</p><h3>Transmission</h3><p>Pelagius' objection survives.</p><h3>Too pessimistic</h3><p>Aquinas: grace perfects nature.</p>",
      thesis:{line:"Augustine's theology of sin is <em>biologically false, morally troubling, and psychologically profound</em>; demythologised, it survives as insight, not doctrine.",unpacking:"The recognition of moral failure remains powerful description."},
      quote:{text:"You have made us for yourself, O Lord, and our heart is restless until it rests in thee.",cite:"Augustine, Confessions I.1"},
      scholars:[{name:"Pelagius",pos:"Denied original sin."},{name:"Schleiermacher",pos:"Universal solidarity in sin, not biological."},{name:"Niebuhr",pos:"Augustinian realism without literal Fall."},{name:"Hampson",pos:"Post-Christian rejection."}],
      exam:"\"Augustine's view of human nature is too pessimistic.\" Discuss. [40]"
    },
    {id:"death-afterlife",title:"Death <em>&amp;</em> the Afterlife",
      spec:["Heaven, hell, purgatory","Election","Sheep and Goats"],
      orientation:"What happens after death? Place, state, or symbol?",
      ao1:"<h3>Heaven, hell, purgatory</h3><p>Place / state / symbol readings.</p><h3>Election</h3><p><strong>Limited</strong> (Calvin), <strong>unlimited</strong> (Arminius), <strong>universalist</strong> (Origen, Hick).</p><h3>Matthew 25</h3><p>Sheep and Goats: judgement on treatment of 'the least of these'.</p>",
      ao2:"<h3>Literalism untenable</h3><p>Pre-modern cosmology.</p><h3>Eternal hell</h3><p>Finite sin cannot deserve infinite punishment. Lewis: doors locked from inside.</p><h3>Universalism</h3><p>Moral seriousness without eternal stakes.</p>",
      thesis:{line:"Heaven and hell are symbolic, <em>universalism is the most morally coherent position</em>, and Christ's criterion in Matthew 25 is ethical rather than creedal.",unpacking:"Spiritual readings preserve the doctrinal point."},
      quote:{text:"The doors of hell are locked on the inside.",cite:"C.S. Lewis"},
      scholars:[{name:"Hick",pos:"Pluralist universalism."},{name:"Lewis",pos:"Hell as chosen separation."},{name:"Hart (David Bentley)",pos:"Universalist defence."},{name:"Wright",pos:"Resurrection of the body."}],
      exam:"\"Hell is a state, not a place.\" Discuss. [40]"
    },
    {id:"knowledge-god",title:"Knowledge of <em>God's Existence</em>",
      spec:["Natural theology","Revealed theology","Fall and knowledge"],
      orientation:"Can we know God by reason alone, or must God reveal himself?",
      ao1:"<h3>Natural knowledge</h3><p>Calvin's <em>sensus divinitatis</em>. Romans 1:20. Aquinas' Five Ways.</p><h3>Revealed knowledge</h3><p>Faith, Christ, Bible, Church.</p><h3>Barth</h3><p>No natural knowledge; revelation alone.</p>",
      ao2:"<h3>Natural theology survives Barth</h3><p>His rejection was motivated by Nazi misuse.</p><h3>Fall</h3><p>Romans 1: suppressed, not absent.</p><h3>Those who never heard</h3><p>Pure exclusivism is nearly indefensible.</p>",
      thesis:{line:"<em>Natural and revealed knowledge work in concert</em>: reason establishes plausibility, revelation supplies content.",unpacking:"Aquinas' integration remains the most coherent Christian position."},
      quote:{text:"Thy word is a lamp unto my feet, and a light unto my path.",cite:"Psalm 119:105"},
      scholars:[{name:"Barth",pos:"No natural theology."},{name:"Brunner",pos:"Modest natural theology."},{name:"Plantinga",pos:"Reformed epistemology."},{name:"Calvin",pos:"Sensus divinitatis."}],
      exam:"\"Knowledge of God can only come from revelation.\" Discuss. [40]"
    },
    {id:"jesus-christ",title:"The Person of <em>Jesus Christ</em>",
      spec:["Son of God","Teacher of wisdom","Liberator"],
      orientation:"Traditional Christianity says all three. Modern theology emphasises liberator and teacher.",
      ao1:"<h3>Son of God</h3><p>Fully divine and human (Chalcedon). 'Abba'. Miracles. Resurrection.</p><h3>Wisdom teacher</h3><p>Prodigal Son. Sermon on the Mount.</p><h3>Liberator</h3><p>Good Samaritan. Temple cleansing. Luke 4:18.</p>",
      ao2:"<h3>Did Jesus think he was divine?</h3><p>Critical historians read him as eschatological prophet.</p><h3>Miracles</h3><p>Hume bites.</p><h3>Wisdom-teacher only?</h3><p>Loses what classical Christianity finds important.</p><h3>Liberator</h3><p>Historically well-attested.</p>",
      thesis:{line:"Jesus was <em>all three</em>: liberator in his mission, teacher in his ethics, Son of God in the faith-claim of the Church.",unpacking:"Picking one impoverishes the others."},
      quote:{text:"Blessed are the poor in spirit, for theirs is the kingdom of heaven.",cite:"Matthew 5:3"},
      scholars:[{name:"Sanders (E.P.)",pos:"Eschatological prophet."},{name:"Wright (N.T.)",pos:"Israel's return from exile."},{name:"Bultmann",pos:"Demythologisation."},{name:"Gutiérrez",pos:"Liberation Christology."}],
      exam:"\"Jesus was no more than a teacher of wisdom.\" Discuss. [40]"
    },
    {id:"moral-principles",title:"Christian Moral <em>Principles</em>",
      spec:["Bible alone","Bible, Church, reason","Agape as sole principle"],
      orientation:"Where does Christian ethics get its authority?",
      ao1:"<h3>Bible alone</h3><p><em>Sola scriptura</em>.</p><h3>Bible, Church, reason</h3><p>Catholic position; magisterium; natural law.</p><h3>Agape alone</h3><p>Fletcher. Mark 12:29-31.</p>",
      ao2:"<h3>Bible alone</h3><p>Bible speaks with many voices.</p><h3>Catholic synthesis</h3><p>Historically vulnerable.</p><h3>Agape alone</h3><p>Reduction is selective.</p>",
      thesis:{line:"Christian ethics requires the <em>threefold authority of scripture, tradition, and reason, integrated by love</em>.",unpacking:"The three work together."},
      quote:{text:"Love is the fulfilling of the law.",cite:"Paul, Romans 13:10"},
      scholars:[{name:"Luther",pos:"Sola scriptura."},{name:"Barth",pos:"Word-derived ethics."},{name:"Hauerwas",pos:"Ecclesial virtue ethics."},{name:"O'Donovan",pos:"Resurrection and moral order."}],
      exam:"\"The Bible is the only authority Christians need on moral issues.\" Discuss. [40]"
    },
    {id:"bonhoeffer",title:"Christian Moral <em>Action</em> · Bonhoeffer",
      spec:["Duty to God and state","Church discipline","Cost of discipleship","Civil disobedience"],
      orientation:"Theology with skin in the game. Sealed by his execution.",
      ao1:"<h3>Background</h3><p>1906-1945. Confessing Church. Barmen Declaration. Hitler plot. Executed Flossenbürg 9 April 1945.</p><h3>Duty and the state</h3><p>Obedience is conditional.</p><h3>Community</h3><p>Finkenwalde seminary. <em>Life Together</em>.</p><h3>Costly grace</h3><p>'When Christ calls a man, he bids him come and die.'</p>",
      ao2:"<h3>Civil disobedience</h3><p>Clear for Nazis; harder for democracies.</p><h3>Cheap grace</h3><p>Critique applies far beyond Weimar.</p><h3>Does he overvalue suffering?</h3><p>Feminist worry. Bonhoeffer meant chosen suffering for the neighbour.</p>",
      thesis:{line:"Bonhoeffer is the <em>most important Christian ethicist of the twentieth century</em> precisely because he paid the cost of his theology with his life.",unpacking:"The integration of thought and deed gives his work weight nothing else matches."},
      quote:{text:"When Christ calls a man, he bids him come and die.",cite:"Bonhoeffer, The Cost of Discipleship"},
      scholars:[{name:"Bethge",pos:"Friend, biographer."},{name:"Hauerwas",pos:"Pacifist alternative."},{name:"Yoder",pos:"Pacifist critique."},{name:"Marsh",pos:"Definitive biography."}],
      exam:"\"Christians should practise civil disobedience.\" Discuss with reference to Bonhoeffer. [40]"
    },
    {id:"pluralism-theology",title:"Religious Pluralism <em>&amp;</em> Theology",
      spec:["Exclusivism","Inclusivism","Pluralism"],
      orientation:"Is Christianity the only way, one way among many, or the final revelation to which others bear incomplete witness?",
      ao1:"<h3>Exclusivism</h3><p><em>Extra ecclesiam nulla salus</em>. John 14:6.</p><h3>Inclusivism</h3><p>Rahner: <strong>anonymous Christians</strong>. Vatican II Nostra Aetate.</p><h3>Pluralism</h3><p>Hick: all major religions are responses to the <strong>Real</strong>.</p>",
      ao2:"<h3>Exclusivism</h3><p>Damns billions.</p><h3>Inclusivism</h3><p>Patronising; but every tradition interprets others.</p><h3>Pluralism</h3><p>Reduces Christ to one revelation among many.</p>",
      thesis:{line:"<em>Inclusivism</em> is the only defensible Christian position on other religions.",unpacking:"Holds Christ's uniqueness and God's universal salvific will."},
      quote:{text:"The Catholic Church rejects nothing that is true and holy in these religions.",cite:"Vatican II, Nostra Aetate"},
      scholars:[{name:"Rahner",pos:"Anonymous Christians."},{name:"Hick",pos:"Pluralist hypothesis."},{name:"D'Costa",pos:"Christian uniqueness."},{name:"Race",pos:"Coined the threefold typology."}],
      exam:"\"Christianity can never accept other religions as equally valid paths to God.\" Discuss. [40]"
    },
    {id:"pluralism-society",title:"Religious Pluralism <em>&amp;</em> Society",
      spec:["Multi-faith societies","Inter-faith dialogue","Scriptural reasoning","Mission"],
      orientation:"How should Christians live alongside adherents of other faiths?",
      ao1:"<h3>Catholic and Anglican responses</h3><p>Redemptoris Missio (1990); Sharing the Gospel of Salvation (1995).</p><h3>Inter-faith dialogue</h3><p>Life, action, theological exchange, religious experience.</p><h3>Scriptural Reasoning</h3><p>Ochs, Ford. Jews, Christians, Muslims study each other's scriptures.</p>",
      ao2:"<h3>Has dialogue worked?</h3><p>Mixed evidence.</p><h3>SR</h3><p>Respects each tradition; practice-based.</p><h3>Mission</h3><p>Must be without coercion in pluralist contexts.</p>",
      thesis:{line:"Multi-faith societies <em>require dialogue not as alternative to mission but as its new form</em>.",unpacking:"Dialogue is the right answer to pluralism."},
      quote:{text:"In a postsecular world, religions must learn to speak their truth without violence.",cite:"David Ford"},
      scholars:[{name:"Newbigin",pos:"Gospel in a pluralist society."},{name:"Ford",pos:"Scriptural Reasoning."},{name:"Williams (Rowan)",pos:"Faith in the public square."},{name:"Eck",pos:"Pluralism Project."}],
      exam:"\"Inter-faith dialogue has contributed little to social cohesion.\" Discuss. [40]"
    },
    {id:"gender-society",title:"Gender <em>&amp;</em> Society",
      spec:["Christian gender teaching","Secular views","Motherhood","Family"],
      orientation:"Christianity in the dock. Feminist critique has reshaped Western assumptions.",
      ao1:"<h3>Traditional teaching</h3><p>Ephesians 5:22-33; 1 Timothy 2:11-15.</p><h3>Mulieris Dignitatem (1988)</h3><p>John Paul II. Equal dignity, 'feminine genius'.</p><h3>Secular views</h3><p>de Beauvoir: 'one is not born, but rather becomes, a woman.' Butler: performativity.</p>",
      ao2:"<h3>Pauline texts</h3><p>Same logic that condemned slavery should apply to gender hierarchy.</p><h3>Secular views</h3><p>Many are improvements.</p><h3>Motherhood</h3><p>Celebration risks confinement.</p>",
      thesis:{line:"Traditional Christian gender teaching <em>contains permanent truths about male-female complementarity and contingent cultural assumptions about subordination</em>.",unpacking:"Theological affirmation of difference without hierarchy."},
      quote:{text:"One is not born, but rather becomes, a woman.",cite:"Simone de Beauvoir"},
      scholars:[{name:"John Paul II",pos:"Mulieris Dignitatem."},{name:"Coakley",pos:"Contemplative theology."},{name:"Trible",pos:"Texts of Terror."},{name:"Butler (Judith)",pos:"Gender Trouble."}],
      exam:"\"Christian teaching should resist current secular views on gender.\" Discuss. [40]"
    },
    {id:"gender-theology",title:"Gender <em>&amp;</em> Theology",
      spec:["Ruether","Daly","Wisdom and nature"],
      orientation:"Can Christianity be reformed from within, or must it be abandoned?",
      ao1:"<h3>Ruether</h3><p>Reform position. Christ's maleness is historically contingent. God as Wisdom (Sophia).</p><h3>Daly</h3><p>'If God is male, then the male is God.' Irretrievably patriarchal.</p><h3>Others</h3><p>Trible: texts of terror. Johnson: <em>She Who Is</em>.</p>",
      ao2:"<h3>Ruether</h3><p>Biblical resources for feminist reform.</p><h3>Daly</h3><p>Other religions also use male language; her exit proves too much.</p><h3>Maleness of Christ</h3><p>What is not assumed is not redeemed (Gregory Nazianzen).</p>",
      thesis:{line:"<em>Ruether is right and Daly is wrong</em>: Christianity is historically patriarchal but not essentially so.",unpacking:"Reform has happened."},
      quote:{text:"If God is male, then the male is God.",cite:"Mary Daly"},
      scholars:[{name:"Ruether",pos:"Reform from within."},{name:"Daly",pos:"Post-Christian rejection."},{name:"Johnson",pos:"She Who Is."},{name:"McFague",pos:"Models of God."}],
      exam:"\"Christianity is essentially sexist.\" Discuss. [40]"
    },
    {id:"secularism",title:"The Challenge of <em>Secularism</em>",
      spec:["Freud and Dawkins","Christianity in public life","Secular humanism"],
      orientation:"Psychological reduction plus political exclusion.",
      ao1:"<h3>Freud</h3><p>Religion as wish-fulfilment.</p><h3>Dawkins</h3><p>The God Delusion (2006).</p><h3>Secular humanism</h3><p>Morality without supernatural belief.</p><h3>Public life</h3><p>Faith schools, House of Lords.</p>",
      ao2:"<h3>Freud</h3><p>Wish-fulfilment explains everything; therefore nothing specific.</p><h3>Dawkins</h3><p>Targets caricatures. Eagleton: 'Tintin in the Congo'.</p><h3>Is spiritual value just human value?</h3><p>MacIntyre: Enlightenment morality retains religious content with substance removed.</p>",
      thesis:{line:"Freud and Dawkins both <em>overreach</em>; secular humanism is a genuine challenge but not a refutation.",unpacking:"Christianity's public role should continue without privileged authority."},
      quote:{text:"Religion is a universal obsessional neurosis of humanity.",cite:"Freud"},
      scholars:[{name:"Dawkins",pos:"Religion as delusion."},{name:"McGrath",pos:"Twilight of Atheism."},{name:"Taylor (Charles)",pos:"A Secular Age."},{name:"Hart (David Bentley)",pos:"Atheist Delusions."}],
      exam:"\"Christianity has no place in public life.\" Discuss. [40]"
    },
    {id:"liberation",title:"Liberation Theology <em>&amp;</em> Marx",
      spec:["Marx on alienation","Liberation theology's use of Marx","Preferential option"],
      orientation:"Gutiérrez and the Boffs fused Marxist social analysis with Catholic theology.",
      ao1:"<h3>Marx</h3><p>Alienation. Exploitation.</p><h3>Liberation theology</h3><p>Marxist analysis as diagnostic tool. <strong>Structural sin</strong>. <strong>Orthopraxis</strong>. Base communities.</p><h3>Preferential option for the poor</h3><p>Now mainstream Catholic teaching.</p>",
      ao2:"<h3>Engaging Marx</h3><p>Ratzinger (1984): risks ideological capture. 1986: legitimate insights.</p><h3>Effective?</h3><p>Mixed historical record.</p><h3>Selectivity</h3><p>Took sociology, left revolutionary politics.</p>",
      thesis:{line:"<em>Liberation theology is the most important Christian ethical movement of the twentieth century after Bonhoeffer</em>; its use of Marx is selective but defensible.",unpacking:"As Aquinas used Aristotle, so liberation theology uses Marx."},
      quote:{text:"The poor are the privileged channel of God's grace.",cite:"Gustavo Gutiérrez"},
      scholars:[{name:"Gutiérrez",pos:"Founding text."},{name:"Boff (Leonardo)",pos:"Brazilian liberationist."},{name:"Sobrino",pos:"Liberation Christology."},{name:"Romero",pos:"Martyred 1980; canonised 2018."},{name:"Cone",pos:"Black liberation theology."}],
      exam:"\"Christian theology should not engage with Marxist ideology.\" Discuss. [40]"
    }
  ]
};
